### ISSUE TITLE
Max cape detected, not max player

### ISSUE THREAD

**Issue by Car-Role** [Skretzo/shortest-path#105] opened 2024-10-14 03:18 UTC
I don't have a max cape but the plugin is telling me to use a max cape

**Comment by Skretzo** [comment] 2024-10-16 18:36
You probably have either `All` or `All (perm)` selected for the `Use teleportation items` config option. Change it to `Inventory` or `Inventory (perm)` to no longer be suggested to use the max cape. However, this does mean that you will no longer be suggested teleportation items that you have unlocked but are not currently carrying in your inventory. Proper inventory item unlock requirements and checking the bank will hopefully be added in a future release, but not sure yet when.

![image](https://github.com/user-attachments/assets/10b9dfd0-c2b0-4d17-a8ec-f886dfafa0c6)

**Comment by Car-Role** [comment] 2024-10-17 04:31
> You probably have either `All` or `All (perm)` selected for the `Use teleportation items` config option. Change it to `Inventory` or `Inventory (perm)` to no longer be suggested to use the max cape. However, this does mean that you will no longer be suggested teleportation items that you have unlocked but are not currently carrying in your inventory. Proper inventory item unlock requirements and checking the bank will hopefully be added in a future release, but not sure yet when.
> 
> ![image](https://private-user-images.githubusercontent.com/53493631/377185759-10b9dfd0-c2b0-4d17-a8ec-f886dfafa0c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzk2ODgsIm5iZiI6MTcyOTEzOTM4OCwicGF0aCI6Ii81MzQ5MzYzMS8zNzcxODU3NTktMTBiOWRmZDAtYzJiMC00ZDE3LWE4ZWMtZjg4NmRmYWZhMGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA0Mjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNDJlOGI2MDcyNTc4YjYyMDk0YTI2NjdmNTFiZmQxOWVjZjQ0MDg4ODUzMDYxMmZjZmU0OGViYzkwM2I0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q28bE5MnKFUk45jAKMP83QnycUItJ09u1mOmoMxBAwM)

![image](https://github.com/user-attachments/assets/860cc6c9-e275-4685-9912-d6a74a8b15a4)


I didn't have it on "all" I had it on Inventory (perm)

I believe this is a bug.

**Comment by Skretzo** [comment] 2024-10-17 08:57
Have you restarted your client in the past 2 weeks? That is necessary to fetch new plugin updates.

Could you please take a screenshot on the world map of the incorrect path you are getting? I am unable to reproduce this issue myself, e.g. by choosing the Crafting Guild as my destination.

**Comment by Car-Role** [comment] 2024-10-18 05:55
Yes I have probably around 20 times

![image](https://github.com/user-attachments/assets/4570437a-cf28-45eb-8597-50a6a3202b42)

I do not have Hunter cape

**Comment by Skretzo** [comment] 2024-10-18 21:48
You are correct, it was incorrectly thinking that the construction cape was a max cape.

This should be fixed in version 1.16.2 and is live in the client as of a few hours ago. Restart the client to fetch the update. Feel free to reopen this issue should it not be properly fixed.

**Closed by Skretzo** 2024-10-18 21:48 UTC
Labels: bug
